//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexaCarModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nexaCarModel()
        {
            this.nexaCarVarients = new HashSet<nexaCarVarient>();
        }
    
        public int id { get; set; }
        public string ModelName { get; set; }
        public string ModelCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nexaCarVarient> nexaCarVarients { get; set; }
    }
}
