//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class nexaCarPrice
    {
        public int id { get; set; }
        public string VarientCode { get; set; }
        public string ColorCode { get; set; }
        public string cityCode { get; set; }
        public string CarPrice { get; set; }
    
        public virtual nexaCarColor nexaCarColor { get; set; }
        public virtual nexaCarVarient nexaCarVarient { get; set; }
    }
}
