---
ID: "ead00c47-a5db-42b1-9180-239090ccf201"
Parent: "aeafbdf8-c651-43a7-8a97-8b13f8e60cbc"
Template: "aeafbdf8-c651-43a7-8a97-8b13f8e60cbc"
Path: /sitecore/templates/Project/Example/Page Type Templates/GenericPage/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211026T105102Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
