---
ID: "3e737c3a-f1d4-4ff3-b0a0-8322b7fa24ba"
Parent: "31e009e9-22f1-4f52-b8ce-789ed95c4880"
Template: "31e009e9-22f1-4f52-b8ce-789ed95c4880"
Path: /sitecore/templates/Foundation/MultiTenant/Folder Templates/Site/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211022T065457Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
